#!/usr/bin/env fish
# Fish Shell Configuration - Installation Script
# This script creates symlinks from dotfiles to ~/.config/fish/

echo "🐟 Fish Shell Configuration - Installation"
echo "=========================================="
echo ""

# Determine dotfiles location
set -l SCRIPT_DIR (dirname (status -f))
set -l DOTFILES_FISH (cd $SCRIPT_DIR/..; and pwd)
set -l CONFIG_DIR $HOME/.config/fish

echo "📂 Dotfiles location: $DOTFILES_FISH"
echo "📂 Target location: $CONFIG_DIR"
echo ""

# Backup existing config if it exists
if test -f $CONFIG_DIR/config.fish
    set -l backup_file $CONFIG_DIR/config.fish.backup.(date +%Y%m%d_%H%M%S)
    echo "💾 Backing up existing config.fish → $backup_file"
    cp $CONFIG_DIR/config.fish $backup_file
end

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p $CONFIG_DIR/{docs,scripts,backups}

# Function to create symlink safely
function create_symlink
    set -l source $argv[1]
    set -l target $argv[2]

    if test -L $target
        # Already a symlink, remove it
        rm $target
    else if test -e $target
        # File exists but not a symlink, backup
        set -l backup_name $target.backup.(date +%Y%m%d_%H%M%S)
        echo "  ⚠️  Backing up existing: "(basename $target)" → "(basename $backup_name)
        mv $target $backup_name
    end

    ln -sf $source $target
    echo "  ✓ Linked: "(basename $target)
end

# Link main configuration files
echo ""
echo "🔗 Creating symlinks for main files..."
create_symlink $DOTFILES_FISH/config.fish $CONFIG_DIR/config.fish
create_symlink $DOTFILES_FISH/CLAUDE.md $CONFIG_DIR/CLAUDE.md
create_symlink $DOTFILES_FISH/.gitignore $CONFIG_DIR/.gitignore

# Link fish_plugins if it exists
if test -f $DOTFILES_FISH/fish_plugins
    create_symlink $DOTFILES_FISH/fish_plugins $CONFIG_DIR/fish_plugins
end

# Link documentation
echo ""
echo "📖 Creating symlinks for documentation..."
for doc in $DOTFILES_FISH/docs/*.md
    set -l doc_name (basename $doc)
    create_symlink $doc $CONFIG_DIR/docs/$doc_name
end

# Link scripts
echo ""
echo "🔧 Creating symlinks for scripts..."
for script in $DOTFILES_FISH/scripts/*.fish
    set -l script_name (basename $script)
    # Don't link install.fish to avoid confusion
    if test $script_name != "install.fish"
        create_symlink $script $CONFIG_DIR/scripts/$script_name
    end
end

# Copy README to config directory (not symlink, as it's different from dotfiles README)
echo ""
echo "📄 Creating config README..."
cat > $CONFIG_DIR/README.md << 'EOF'
# 🐟 Fish Shell Configuration

This directory contains a well-organized Fish shell configuration optimized for modern development workflows.

**Source:** This configuration is managed in dotfiles repository via symlinks.
**Location:** `~/ghq/github.com/nwiizo/dotfiles/fish/`

## 📁 Directory Structure

```
~/.config/fish/
├── README.md                  ← This file (local)
├── config.fish                ← Symlinked from dotfiles
├── CLAUDE.md                  ← Symlinked from dotfiles
├── .gitignore                 ← Symlinked from dotfiles
├── fish_plugins               ← Symlinked from dotfiles
│
├── docs/                      ← Symlinked documentation
│   ├── QUICK_REFERENCE.md
│   ├── CHANGES_EXPLAINED.md
│   └── ASYNC_PROMPT_ISSUE.md
│
├── scripts/                   ← Symlinked scripts
│   └── test_config.fish
│
├── backups/                   ← Local backups (not in dotfiles)
│
├── completions/               ← Generated by plugins
├── conf.d/                    ← Generated by plugins
├── functions/                 ← Generated by plugins
├── fish_variables             ← Local state (not in dotfiles)
└── local.fish                 ← Machine-specific (gitignored)
```

## 🔄 Updating Configuration

Since files are symlinked from dotfiles:

```bash
# Pull latest changes
cd ~/ghq/github.com/nwiizo/dotfiles
git pull

# Changes are immediately reflected (symlinks!)
# Just reload Fish
exec fish
```

## 📚 Documentation

See symlinked files for complete documentation:
- **docs/QUICK_REFERENCE.md** - Troubleshooting
- **docs/CHANGES_EXPLAINED.md** - Detailed changes
- **CLAUDE.md** - AI guidelines

## 🆘 Problems?

```bash
# Run diagnostic
fish ~/.config/fish/scripts/test_config.fish

# Check symlinks
ls -la ~/.config/fish/*.fish
ls -la ~/.config/fish/docs/
ls -la ~/.config/fish/scripts/
```

**Dotfiles Repository:** https://github.com/nwiizo/dotfiles
EOF

echo "  ✓ Created: README.md"

# Check for required tools
echo ""
echo "🔍 Checking for required tools..."
set -l missing_tools

for tool in starship eza bat rg fzf zoxide mise
    if not type -q $tool
        echo "  ✗ $tool - NOT FOUND"
        set missing_tools $missing_tools $tool
    else
        echo "  ✓ $tool - installed"
    end
end

# Check for Fisher
echo ""
if functions -q fisher
    echo "✓ Fisher plugin manager - installed"
else
    echo "⚠️  Fisher plugin manager - NOT FOUND"
    echo ""
    echo "Install Fisher with:"
    echo "  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
    set missing_tools $missing_tools fisher
end

# Summary
echo ""
echo "=========================================="
echo "📊 Installation Summary"
echo "=========================================="
echo ""

if test (count $missing_tools) -eq 0
    echo "✅ All required tools are installed!"
else
    echo "⚠️  Missing tools: "(string join ", " $missing_tools)
    echo ""
    echo "Install missing tools:"
    echo "  brew install "(string join " " $missing_tools)
end

echo ""
echo "🎉 Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Install missing tools (if any)"
echo "  2. Install Fisher plugins: fisher update"
echo "  3. Reload Fish: exec fish"
echo "  4. Verify: fish ~/.config/fish/scripts/test_config.fish"
echo ""
echo "📖 Documentation: ~/.config/fish/docs/"
echo "🔧 Diagnostics: fish ~/.config/fish/scripts/test_config.fish"
echo ""
